//
// Created by qianlu on 2020/5/27.
//

#ifndef SNLCOMPILER_WORD_HPP
#define SNLCOMPILER_WORD_HPP

#include <string>

enum Word{
    PROGRAM,TYPE,VAR,PROCEDURE,BEGIN,END,ARRAY,OF,RECORD,IF,THEN,
    ELSE,FI,WHILE,DO,ENDWH,READ,WRITE,RETURN,INTEGER,CHAR,
    UNSIGNEDNUMBER,
    ADD,SUB,MUL,DIV,LESS,EQUAL,LEFT_PARENT,RIGHT_PARENT,
    LEFT_BRACKET,RIGHT_BRACKET,DOT,SEMICOLON,EoF,SPACE,
    COLON_EQUAL,LEFT_BRACES,RIGHT_BRACES,APOSTROPHE,TWO_DOT,
    COMMA,
    IDENTIFIERS
};

#endif //SNLCOMPILER_WORD_HPP
